#ifndef TPXSERVER_SERVERCODES_H
#define TPXSERVER_SERVERCODES_H

#include <cstdint>

enum class ServerCommand : std::uint32_t {

    NOP = 0,

// Commands to control the Timepix
    GET_SOFTWARE_VERSION = 1,
    GET_FIRMWARE_VERSION = 2,

    GET_CAMERA_ID = 3,
    GET_DEVICE_IDS = 4,
    GET_LOCAL_TEMP = 5,
    GET_REMOTE_TEMP = 6,
    GET_FPGA_TEMP = 7,
    GET_FAN_SPEED = 8,
    GET_PRESSURE = 9,
    GET_HUMIDITY = 10,

    GET_SPIDR_ADC = 11,
    SET_BIAS_VOLTAGE = 12,
    SET_BIAS_SUPPLY_ENABLED = 13,

    GET_DEVICE_PORT = 14,
    GET_SERVER_PORT = 15,
    SET_SERVER_PORT = 16,

    SET_TOA_DECODERS_ENABLED = 17,

    RESTART_TIMERS = 18,
    RESET_TIMERS = 19,

    RESET_PIXELS = 20,

    GET_SPIDR_REGISTER = 21,
    SET_SPIDR_REGISTER = 22,

    GET_PLL_CONFIG = 23,
    SET_PLL_CONFIG = 24,

    GET_HEADER_FILTER = 25,
    SET_HEADER_FILTER = 26,

    GET_GEN_CONFIG = 27,
    SET_GEN_CONFIG = 28,

    GET_PERIOD_PHASE = 29,
    SET_PERIOD_PHASE = 30,

    GET_TRIGGER_CONF = 31,
    SET_TRIGGER_CONF = 32,

    GET_DAC = 33,
    SET_DAC = 34,

    START_READOUT = 35,
    STOP_READOUT = 36,

    AUTOTRIG_START = 37,
    AUTOTRIG_STOP = 38,

    GET_PIXEL_CONFIG = 39,
    SET_PIXEL_CONFIG = 40,

    RESET_MODULE = 41,
    GET_READOUT_SPEED = 42,

    SET_SENSEDAC = 48,

// Commands to control the UDP server
    SET_UDP_PORT = 500,
    SET_RAW_TPX3_PATH = 501,
    GET_RAW_DATA_SERVER_PATH = 502,

// Commands to control the clustering server
    GET_CLUSTER_SERVER_PATH = 600,
    SET_CLUSTER_INPUT_SERVER = 601,
    SET_CLUSTER_PARAMETERS = 602,
    FLUSH_CLUSTERS = 603,

// Error codes
    INVALID_COMMAND_DATA = 993,
    CANT_OPEN_FILE = 994,
    THREAD_NOT_CONNECTED = 995,
    THREAD_NOT_STARTED = 996,
    SERVER_RESET = 997,
    ERROR_OCCURED = 998,
    UNKNOWN_COMMAND = 999

};

#endif //TPXSERVER_SERVERCODES_H
